export const Function = 'function'
export const Var = 'var'
export const Keyword = 'keyword'
export const Directory = 'directory'
export const Script = 'script'
export const Property = 'property'
export const Method = 'method'
